spring.application.name=fairsharebackend

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=fairshare
spring.jpa.defer-datasource-initialization=true

jwt.secret=YzA5ODQ3ZjU1YjQxYjE2ZjQwY2RlYmUyNjY2N2NhY2U0YjYxYzQyMg==