spring.application.name=fairsharebackend

spring.datasource.url=jdbc:mysql://localhost:3306/fairshare
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

#Temp
jwt.secret=YzA5ODQ3ZjU1YjQxYjE2ZjQwY2RlYmUyNjY2N2NhY2U0YjYxYzQyMg==