spring.application.name=fairsharebackend

spring.datasource.url= #TODO - replace
spring.datasource.username= #TODO - replace
spring.datasource.password= #TODO - replace

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true